# Generated by Django 5.2.5 on 2025-08-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sghss", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("descricao", models.TextField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sghss.funcionario",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sghss.paciente"),
                ),
            ],
        ),
    ]
