# Generated by Django 5.2.5 on 2025-08-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sghss", "0002_consulta"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="concluida",
            field=models.BooleanField(default=False),
        ),
    ]
